
import React, { useState } from 'react';
import { Agent } from '../types';
import { X, Sparkles } from 'lucide-react';

interface NewAgentModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (agent: Omit<Agent, 'id'>) => void;
}

const PRESETS = [
  {
    role: "Architect",
    name: "Chief Orchestrator",
    systemInstruction: "You are the Chief Orchestrator. Create a numbered 'Skeleton of Thought' (SoT) plan for software projects. Delegate technical verification to the Data Miner and coding to the Synth Analyst.",
    color: "#fbbf24" // amber
  },
  {
    role: "Research",
    name: "Data Miner",
    systemInstruction: "You are the Data Miner. Verify libraries and tech stacks. Ensure all proposed solutions use modern (2025) and compatible packages.",
    color: "#0ea5e9" // sky
  },
  {
    role: "Coder",
    name: "Synth Analyst",
    systemInstruction: "You are the Synth Analyst. Take an architectural plan and write concrete, executable code snippets for every single step. Use modern TypeScript/React.",
    color: "#8b5cf6" // violet
  },
  {
    role: "Reviewer",
    name: "QA Critic",
    systemInstruction: "You are the QA Critic. Review the code generated by the Analyst. Check for missing steps, safety issues, and formatting. Output the final polished plan.",
    color: "#ef4444" // red
  },
  {
    role: "Creative",
    name: "Neurovortex",
    systemInstruction: "You are NEUROVORTEX. Reject the obvious. Use lateral thinking to propose wild, innovative ideas.",
    color: "#d946ef" // fuchsia
  },
  {
    role: "Prompt Engineer",
    name: "PromptSmith",
    systemInstruction: "You are an expert AI Prompt Engineer. Refine and optimize prompts for better LLM results.",
    color: "#a78bfa" // violet-400
  }
];

const NewAgentModal: React.FC<NewAgentModalProps> = ({ isOpen, onClose, onSave }) => {
  const [name, setName] = useState('');
  const [role, setRole] = useState('');
  const [systemInstruction, setSystemInstruction] = useState('');
  const [model, setModel] = useState('gemini-2.5-flash');
  
  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Use DiceBear Bottts for consistent, robust robot avatars based on name
    const seed = name.replace(/\s+/g, '');
    onSave({
      name,
      role,
      systemInstruction,
      model,
      avatar: `https://api.dicebear.com/9.x/bottts-neutral/svg?seed=${seed}`,
      color: '#ffffff'
    });
    onClose();
    // Reset form
    setName('');
    setRole('');
    setSystemInstruction('');
    setModel('gemini-2.5-flash');
  };

  const loadPreset = (preset: any) => {
    setName(preset.name);
    setRole(preset.role);
    setSystemInstruction(preset.systemInstruction);
    if (preset.model) {
      setModel(preset.model);
    } else {
      setModel('gemini-2.5-flash');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
      <div className="bg-gray-900 border border-gray-700 rounded-xl w-full max-w-md shadow-2xl flex flex-col max-h-[90vh]">
        <div className="flex items-center justify-between p-4 border-b border-gray-800">
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-yellow-400" />
            Deploy New Agent
          </h3>
          <button onClick={onClose} className="text-gray-400 hover:text-white">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-4 border-b border-gray-800 bg-gray-800/50">
          <p className="text-xs text-gray-400 mb-2 font-semibold">QUICK PRESETS</p>
          <div className="flex gap-2 flex-wrap">
            {PRESETS.map(p => (
              <button
                key={p.name}
                type="button"
                onClick={() => loadPreset(p)}
                className="px-3 py-1.5 rounded-full bg-gray-800 border border-gray-700 hover:border-blue-500 hover:text-blue-400 text-xs font-medium text-gray-300 transition-colors"
              >
                {p.role}
              </button>
            ))}
          </div>
        </div>

        <form onSubmit={handleSubmit} className="p-4 space-y-4 overflow-y-auto">
          <div>
            <label className="block text-xs font-medium text-gray-400 mb-1">Agent Name</label>
            <input
              required
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full bg-gray-800 border border-gray-700 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-600 focus:outline-none"
              placeholder="e.g. Architect"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-400 mb-1">Role / Function</label>
            <input
              required
              value={role}
              onChange={(e) => setRole(e.target.value)}
              className="w-full bg-gray-800 border border-gray-700 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-600 focus:outline-none"
              placeholder="e.g. System Design"
            />
          </div>
          
          <div>
            <label className="block text-xs font-medium text-gray-400 mb-1">Model</label>
            <select
              value={model}
              onChange={(e) => setModel(e.target.value)}
              className="w-full bg-gray-800 border border-gray-700 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-600 focus:outline-none text-sm"
            >
              <option value="gemini-2.5-flash">Gemini 2.5 Flash (Fast)</option>
              <option value="gemini-3-pro-preview">Gemini 3 Pro Preview (Reasoning)</option>
            </select>
          </div>

          <div>
            <label className="block text-xs font-medium text-gray-400 mb-1">System Instruction (Persona)</label>
            <textarea
              required
              value={systemInstruction}
              onChange={(e) => setSystemInstruction(e.target.value)}
              rows={4}
              className="w-full bg-gray-800 border border-gray-700 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-600 focus:outline-none resize-none"
              placeholder="Define how this agent should behave..."
            />
          </div>

          <div className="pt-2">
            <button
              type="submit"
              className="w-full py-3 rounded-lg bg-blue-600 hover:bg-blue-500 text-white font-medium transition-colors"
            >
              Initialize Agent
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default NewAgentModal;
